<Project Sdk="Microsoft.Build.NoTargets">
  <PropertyGroup>
    <SkipBuild Condition="'$(BuildSdkDeb)' != 'true'">true</SkipBuild>
    <TargetFramework>$(SdkTargetFramework)</TargetFramework>
    <RuntimeIdentifier>$(NETCoreSdkRuntimeIdentifier)</RuntimeIdentifier>
    <GenerateInstallers>true</GenerateInstallers>
    <BuildDebPackage>true</BuildDebPackage>
    <ProductBrandPrefix>Microsoft .NET</ProductBrandPrefix>
    <LicenseFile>$(RepoRoot)LICENSE.TXT</LicenseFile>
    <InstallerName>dotnet-sdk</InstallerName>
    <InstallerName Condition="'$(TargetOS)' == 'osx'">dotnet-sdk-internal</InstallerName>
    <PackageBrandNameSuffix>Host FX Resolver</PackageBrandNameSuffix>
    <PlatformPackageType>ToolPack</PlatformPackageType>
    <UseBrandingNameInLinuxPackageDescription>true</UseBrandingNameInLinuxPackageDescription>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\redist-installer\redist-installer.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.Build.Tasks.Installers" />
  </ItemGroup>

  <Import Project="..\redist-installer\targets\BuildCoreSdkTasks.targets" />
  <Import Project="..\redist-installer\targets\LinuxNativeInstallerDependencyVersions.targets" />

  <PropertyGroup>
    <!--
      TODO: how can we have this discovered, or moved?
      Previous value, that was copied from old project was:
      $(BaseOutputPath)$(Configuration)\dotnet\
    -->
    <RedistLayoutPath>$(ArtifactsBinDir)redist-installer\$(Configuration)\dotnet\</RedistLayoutPath>
    <ManpagesDirectory>$(RepoRoot)Documentation/manpages</ManpagesDirectory>
    <CLISdkRoot>$(RedistLayoutPath)sdk/</CLISdkRoot>
    <TemplatesRoot>$(RedistLayoutPath)templates/</TemplatesRoot>
  </PropertyGroup>


  <Target Name="PublishToDisk">
    <Error Condition="'$(OutputPath)' == ''" Text="Publishing to disk requires the OutputPath to be set to the root of the path to write to." />

    <ItemGroup>
      <CLISdkFiles Include="$(CLISdkRoot)**/*" />
      <TemplatesFiles Include="$(TemplatesRoot)**/*" />
      <SdkDebManPageFiles Include="$(ManpagesDirectory)/**/*" />
      <ManifestFiles Include="$(RedistLayoutPath)sdk-manifests/**/*" />
    </ItemGroup>

    <!-- Create layout: Binaries -->
    <Copy
      DestinationFiles="@(CLISdkFiles->'$(OutputPath)/sdk/%(RecursiveDir)%(Filename)%(Extension)')"
      SourceFiles="@(CLISdkFiles)"
      OverwriteReadOnlyFiles="True"
      SkipUnchangedFiles="False"
      UseHardlinksIfPossible="False" />

    <!-- Create layout: Templates -->
    <Copy
      DestinationFiles="@(TemplatesFiles->'$(OutputPath)/templates/%(RecursiveDir)%(Filename)%(Extension)')"
      SourceFiles="@(TemplatesFiles)"
      OverwriteReadOnlyFiles="True"
      SkipUnchangedFiles="False"
      UseHardlinksIfPossible="False" />

    <!-- Create layout: Workload Manifests -->
    <Copy
      DestinationFiles="@(ManifestFiles->'$(OutputPath)/sdk-manifests/%(RecursiveDir)%(Filename)%(Extension)')"
      SourceFiles="@(ManifestFiles)"
      OverwriteReadOnlyFiles="True"
      SkipUnchangedFiles="False"
      UseHardlinksIfPossible="False" />

    <!-- TODO: figure out this section -->
    <!-- Create layout: Man Pages
    <Copy
      DestinationFiles="@(SdkDebManPageFiles->'$(LayoutDocsDir)/%(RecursiveDir)%(Filename)-$(Version)%(Extension)')"
      SourceFiles="@(SdkDebManPageFiles)"
      OverwriteReadOnlyFiles="True"
      SkipUnchangedFiles="False"
      UseHardlinksIfPossible="False" />
    -->

    <!-- TODO: figure out this section -->
    <!-- Create layout: Generate and Place postinst
    <ReplaceFileContents
      InputFiles="$(DebianPostinstTemplateFile)"
      DestinationFiles="$(DebianPostinstFile)"
      ReplacementItems="@(DebianPostInstTokenValues)" />

    <Chmod
      Glob="$(DebianPostinstFile)"
      Mode="ugo+x" />
    -->

    <!-- TODO: likely need to set properties instead of using config.json - check -->
    <!-- Create layout: Generate and Place debian_config.json
    <ReplaceFileContents
      InputFiles="$(DebianConfigTemplateFile)"
      DestinationFiles="$(DebianConfigJsonFile)"
      ReplacementItems="@(DebianConfigTokenValues)" />
    -->

  </Target>

  <Target Name="AddLinuxPackageInformation"
      BeforeTargets="GetDebInstallerJsonProperties;GetRpmInstallerJsonProperties"
      DependsOnTargets="CalculateLinuxNativeInstallerDependencyVersions">
    <ItemGroup>
      <LinuxPackageDependency Include="dotnet-runtime-$(MicrosoftNETCoreAppMajorMinorVersion)" Version="$(MicrosoftNETCoreAppRuntimePackageVersionWithTilde)" />
      <LinuxPackageDependency Include="dotnet-targeting-pack-$(MicrosoftNETCoreAppMajorMinorVersion)" Version="$(MicrosoftNETCoreAppRefPackageVersionWithTilde)" />
      <LinuxPackageDependency Include="dotnet-apphost-pack-$(MicrosoftNETCoreAppMajorMinorVersion)" Version="$(MicrosoftNETCoreAppRuntimePackageVersionWithTilde)" />
      <LinuxPackageDependency Include="netstandard-targeting-pack-$(NetStandardTargetingPackMajorMinorVersion)" Version="$(NetStandardTargetingPackPackageVersionWithTilde)" />
      <LinuxPackageDependency Include="aspnetcore-runtime-$(AspNetCoreMajorMinorVersion)" Version="$(AspNetCoreRuntimeVersionWithTilde)" />
      <LinuxPackageDependency Include="aspnetcore-targeting-pack-$(AspNetCoreMajorMinorVersion)" Version="$(AspNetCoreRefVersionWithTilde)" />
      <RpmJsonProperty Include="directories" Object="[ &quot;/usr/share/dotnet&quot;, &quot;/usr/share/doc/$(VersionedInstallerName)&quot; ]" />
    </ItemGroup>
  </Target>
</Project>
